---
# File: roles/systools/tasks/main.yml

- name:         install | ensure that non-free packages are used
  replace:
    dest:       /etc/apt/sources.list
    regexp:     '(^deb(-src?) http(s?):\/\/.*\/.* main$)'
    replace:    '\1 non-free'

- name:         install | enforce update of apt cache
  apt:          update_cache=yes

- name:         install | ensure that vim is installed
  apt:          name="{{item}}" state=latest update_cache=yes cache_valid_time=3600
  with_items:   "{{sys_packages}}"
  when:         "{{sys_packages}}"

- name:         git | Clone oh-my-zsh repo
  git:          repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/root/.oh-my-zsh update=no

- name:         file | Create conf folder in home directory
  file:         path=/root/conf/ state=directory owner="{{user}}"

- name:         template | deploy .zshrc
  template:     src=roles/systools/templates/zshrc.in dest=/root/conf/zshrc owner={{user}}

- name:         file | remove standard zshrc
  file:         path=/root/.zshrc state=absent

- name:         file | symlink zshrc
  file:         path=/root/.zshrc src=/root/conf/zshrc state=link owner={{user}}

- name:         user | Set zsh as default shell
  user:         name={{user}} shell=/bin/zsh

- name:         copy | disable ipv6 on every boot
  copy:         src=roles/systools/templates/01-disable-ipv6.conf dest=/etc/sysctl.d/01-disable-ipv6.conf owner={{user}} mode="u+x"

- name:         command | disable ipv6 now
  command:      echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6